# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 245)
        Form.setMinimumSize(QtCore.QSize(395, 245))
        Form.setMaximumSize(QtCore.QSize(395, 245))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.map2pdf = QtWidgets.QCheckBox(self.groupBox)
        self.map2pdf.setChecked(True)
        self.map2pdf.setTristate(False)
        self.map2pdf.setObjectName("map2pdf")
        self.gridLayout.addWidget(self.map2pdf, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mapNote = QtWidgets.QCheckBox(self.groupBox)
        self.mapNote.setChecked(True)
        self.mapNote.setTristate(False)
        self.mapNote.setObjectName("mapNote")
        self.horizontalLayout_4.addWidget(self.mapNote)
        self.mapStep = QtWidgets.QComboBox(self.groupBox)
        self.mapStep.setMinimumSize(QtCore.QSize(0, 25))
        self.mapStep.setObjectName("mapStep")
        self.horizontalLayout_4.addWidget(self.mapStep)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.deleteNote = QtWidgets.QCheckBox(self.groupBox)
        self.deleteNote.setChecked(True)
        self.deleteNote.setTristate(False)
        self.deleteNote.setObjectName("deleteNote")
        self.gridLayout.addWidget(self.deleteNote, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selPath = QtWidgets.QPushButton(Form)
        self.selPath.setMinimumSize(QtCore.QSize(0, 30))
        self.selPath.setObjectName("selPath")
        self.horizontalLayout_2.addWidget(self.selPath)
        self.outputPath = QtWidgets.QLineEdit(Form)
        self.outputPath.setMinimumSize(QtCore.QSize(0, 30))
        self.outputPath.setObjectName("outputPath")
        self.horizontalLayout_2.addWidget(self.outputPath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runProgram = QtWidgets.QPushButton(Form)
        self.runProgram.setMinimumSize(QtCore.QSize(0, 30))
        self.runProgram.setObjectName("runProgram")
        self.horizontalLayout.addWidget(self.runProgram)
        self.exitProgram = QtWidgets.QPushButton(Form)
        self.exitProgram.setMinimumSize(QtCore.QSize(0, 30))
        self.exitProgram.setObjectName("exitProgram")
        self.horizontalLayout.addWidget(self.exitProgram)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "工程自动化标注"))
        self.label_2.setText(_translate("Form", "自动标注坐标程序"))
        self.groupBox.setTitle(_translate("Form", "基本信息"))
        self.map2pdf.setText(_translate("Form", "图纸转PDF"))
        self.mapNote.setText(_translate("Form", "标注图纸"))
        self.deleteNote.setText(_translate("Form", "删除标记"))
        self.selPath.setText(_translate("Form", "输出路径："))
        self.runProgram.setToolTip(_translate("Form", "点击运行脚本..."))
        self.runProgram.setStatusTip(_translate("Form", "点击运行脚本..."))
        self.runProgram.setText(_translate("Form", "运行"))
        self.exitProgram.setToolTip(_translate("Form", "点击退出脚本..."))
        self.exitProgram.setStatusTip(_translate("Form", "点击退出脚本..."))
        self.exitProgram.setText(_translate("Form", "退出"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">有任何需求请联系-&gt;Robot QQ:502614708,微信号:Robot_0101 </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">版本信息：Copyright (C) 2023.07.07 V1.02</p></body></html>"))
#import icon_rc
